"""update table 

Revision ID: 0273ac8fa792
Revises: c91eac4b5d16
Create Date: 2024-12-18 11:12:59.209283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0273ac8fa792'
down_revision: Union[str, None] = 'c91eac4b5d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
