"""Add Admin table

Revision ID: fcc22e451984
Revises: a1b16ec56cc5
Create Date: 2024-12-18 12:53:07.003455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc22e451984'
down_revision: Union[str, None] = 'a1b16ec56cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'blog_id')
    op.drop_table('admins')
    # ### end Alembic commands ###
